### ISSUE TITLE
Error compiling beacon example in Arduino IDE

### ISSUE THREAD

**Issue by korish** [adafruit/Adafruit_nRF52_Arduino#131]
I've followed the instructions in the following [link](https://learn.adafruit.com/bluefruit-nrf52-feather-learning-guide?view=all#1-bsp-installation) and tried to compile the beacon example in peripheral section. Arduino IDE is version 1.8.5. OS: Linux Ubuntu 16.04 x64.

Here is the traceback.

Traceback (most recent call last):
  File "/usr/local/bin/nrfutil", line 9, in <module>
    load_entry_point('nrfutil==0.3.0.0', 'console_scripts', 'nrfutil')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/nrfutil-0.3.0.0-py2.7.egg/nordicsemi/__main__.py", line 276, in genpkg
    package.generate_package(zipfile_path)
  File "/usr/local/lib/python2.7/dist-packages/nrfutil-0.3.0.0-py2.7.egg/nordicsemi/dfu/package.py", line 253, in generate_package
    init_packet = self._create_init_packet(firmware, self.is_mesh)
  File "/usr/local/lib/python2.7/dist-packages/nrfutil-0.3.0.0-py2.7.egg/nordicsemi/dfu/package.py", line 356, in _create_init_packet
    return p.generate_packet()
  File "/usr/local/lib/python2.7/dist-packages/nrfutil-0.3.0.0-py2.7.egg/nordicsemi/dfu/init_packet.py", line 100, in generate_packet
    return struct.pack(format_string, *args)
struct.error: pack expected 6 items for packing (got 7)
exit status 1
Error compiling for board Adafruit Bluefruit nRF52 Feather.

**Comment by korish** [comment]
After running commands from Step 2 of the documentation the issue was resolved.

$ cd tools/nrfutil-0.5.2
$ sudo pip install -r requirements.txt
$ sudo python setup.py install

 Sorry for the noise.
