### ISSUE TITLE
Can't verify / upload a sketch - RuntimeError: Click will abort further execution because Python was configured to use ASCII

### ISSUE THREAD

**Issue by NicolasMas** [adafruit/Adafruit_nRF52_Arduino#823]
### Operating System

MacOS

### IDE version

Arduino: 2.3.2

### Board

Feather nRF52840 express

### BSP version

github latest

### Sketch

// Basic Blink Sketch for Adafruit Feather nRF52840
// Smoke test code

// The onboard LED is connected to pin 13 on the Feather nRF52840
#define LED_PIN 13

void setup() {
  // Initialize the digital pin as an output.
  pinMode(LED_PIN, OUTPUT);
}

void loop() {
  // Turn the LED on (HIGH is the voltage level)
  digitalWrite(LED_PIN, HIGH);
  // Wait for a second
  delay(1000);
  // Turn the LED off by making the voltage LOW
  digitalWrite(LED_PIN, LOW);
  // Wait for a second
  delay(1000);
}

### What happened ?

Can get the code to be verified and or uploaded. Can't burn the bootloader either.

Note: lost as to where to open this issue, so I defaulted to this repo. Seems like a known issue with a relationship to the `adafruit-nrfutil` tool https://github.com/adafruit/Adafruit_nRF52_nrfutil/blob/1361059009ff6a24d63b37eb3a4b28127837ead2/README.md

### How to reproduce ?

MacOS Sonoma latest version, python from brew latest version
Paste the code
Verify/upload

### Debug Log

Traceback (most recent call last):
  File "__main__.py", line 317, in <module>
  File "click/core.py", line 1137, in __call__
  File "click/core.py", line 1043, in main
  File "click/_unicodefun.py", line 100, in _verify_python_env
RuntimeError: Click will abort further execution because Python was configured to use ASCII as encoding for the environment. Consult https://click.palletsprojects.com/unicode-support/ for mitigation steps.

This system lists some UTF-8 supporting locales that you can pick from. The following suitable locales were discovered: af_ZA.UTF-8, am_ET.UTF-8, be_BY.UTF-8, bg_BG.UTF-8, ca_ES.UTF-8, cs_CZ.UTF-8, da_DK.UTF-8, de_AT.UTF-8, de_CH.UTF-8, de_DE.UTF-8, el_GR.UTF-8, en_AU.UTF-8, en_CA.UTF-8, en_GB.UTF-8, en_IE.UTF-8, en_NZ.UTF-8, en_US.UTF-8, es_ES.UTF-8, et_EE.UTF-8, eu_ES.UTF-8, fi_FI.UTF-8, fr_BE.UTF-8, fr_CA.UTF-8, fr_CH.UTF-8, fr_FR.UTF-8, he_IL.UTF-8, hr_HR.UTF-8, hu_HU.UTF-8, hy_AM.UTF-8, is_IS.UTF-8, it_CH.UTF-8, it_IT.UTF-8, ja_JP.UTF-8, kk_KZ.UTF-8, ko_KR.UTF-8, lt_LT.UTF-8, nl_BE.UTF-8, nl_NL.UTF-8, no_NO.UTF-8, pl_PL.UTF-8, pt_BR.UTF-8, pt_PT.UTF-8, ro_RO.UTF-8, ru_RU.UTF-8, sk_SK.UTF-8, sl_SI.UTF-8, sr_YU.UTF-8, sv_SE.UTF-8, tr_TR.UTF-8, uk_UA.UTF-8, zh_CN.UTF-8, zh_HK.UTF-8, zh_TW.UTF-8
[1721] Failed to execute script '__main__' due to unhandled exception!

exit status 1

Compilation error: exit status 1

### Screenshots

![image](https://github.com/adafruit/Adafruit_nRF52_Arduino/assets/1871481/0497d578-f810-48aa-a7fb-f4b4a94521cc)

**Comment by per1234** [comment]
There was a previous report of this at https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/743.

It was closed as resolved because, for some users (including myself) the fault only occurs when using older versions of the platform, and does not occur when using the latest versions. I provided details about that here (and I just verified it is still true for the latest version 1.6.1):

https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/743#issuecomment-1386395822

However, other users reported that they still encounter the problem even when using the latest (at the time) version of the platform. Those users reported they found that installing a standalone copy of the troubled "adafruit-nrfutil" tool was an effective workaround:

https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/743#issuecomment-1903751213

If those instructions aren't clear, I wrote more detailed instructions here:

https://forum.arduino.cc/t/python-utf-8-compile-error-macos-sequoia/1373103/7
